[package]
name = "ruPRIM-host"
edition = "2024"
authors = [ "Dilshod Tadjibaev (@antimora)",]
license = "MIT OR Apache-2.0"
description = "ruPRIM CPU tensor primitives, reductions, indexing and SIMD kernels."
readme = "README.md"
build = false
repository = "https://github.com/shuqi2077/RUDA"

[lib]
name = "ruprim_host"
path = "src/lib.rs"

[features]
default = [ "std", "simd", "rayon",]
std = [ "ruda-core/std", "half/std", "num-traits/std",]
simd = [ "dep:macerator", "dep:aligned-vec",]
rayon = [ "dep:rayon", "ruda-core/tensor-host-parallel",]

[package.version]
workspace = true

[dependencies.bytemuck]
version = "1.25.0"

[dependencies.half]
version = "2.7.1"
features = [ "alloc", "num-traits", "serde",]
default-features = false

[dependencies.num-traits]
version = "0.2.19"
features = [ "libm",]
default-features = false

[dependencies.libm]
version = "0.2.15"

[dependencies.macerator]
version = "0.3.0"
optional = true

[dependencies.aligned-vec]
version = "0.6"
optional = true
default-features = false

[dependencies.rayon]
version = "1.10.0"
optional = true

[dependencies.ruda-core]
path = "../../ruda-core"
version = "0.1.0"
default-features = false
features = [ "tensor-host-storage",]
